# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SimpleTemp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'Stripe'
  pod 'Firebase/Messaging'

  # Pods for SimpleTemp

  target 'SimpleTempTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'SimpleTempUITests' do
    # Pods for testing
  end

end
